const commonEnv = require('./env_dev.common');

module.exports = {
    apps: [
        {
            name: 'tp-gw',
            script: '../api-gateway/dist/main.js',
            instances: 1,
            exec_mode: 'fork',
            watch: false,
            autorestart: false,
            max_memory_restart: '8192M',
            env: { ...commonEnv },
        },
        {
            name: 'tp-auth',
            script: '../microservice-auth/dist/main.js',
            instances: 1,
            exec_mode: 'fork',
            watch: false,
            autorestart: false,
            max_memory_restart: '8192M',
            env: { ...commonEnv },
        },
        {
            name: 'tp-hr',
            script: '../microservice-hr/dist/main.js',
            instances: 1,
            exec_mode: 'fork',
            watch: false,
            autorestart: false,
            max_memory_restart: '8192M',
            env: { ...commonEnv },
        },
        {
            name: 'tp-produce',
            script: '../microservice-produce/dist/main.js',
            instances: 1,
            exec_mode: 'fork',
            watch: false,
            autorestart: false,
            max_memory_restart: '8192M',
            env: { ...commonEnv },
        },
        {
            name: 'tp-purchase',
            script: '../microservice-purchase/dist/main.js',
            instances: 1,
            exec_mode: 'cluster',
            watch: false,
            autorestart: false,
            max_memory_restart: '8192M',
            env: { ...commonEnv },
        },
        {
            name: 'tp-qc',
            script: '../microservice-qc/dist/main.js',
            instances: 1,
            exec_mode: 'cluster',
            watch: false,
            autorestart: false,
            max_memory_restart: '8192M',
            env: { ...commonEnv },
        },
        {
            name: 'tp-sp',
            script: '../microservice-sp/dist/main.js',
            instances: 1,
            exec_mode: 'fork',
            watch: false,
            autorestart: false,
            max_memory_restart: '8192M',
            env: { ...commonEnv },
        },
        {
            name: 'tp-warehouse',
            script: '../microservice-warehouse/dist/main.js',
            instances: 1,
            exec_mode: 'fork',
            watch: false,
            autorestart: false,
            max_memory_restart: '8192M',
            env: { ...commonEnv },
        },
        {
            name: 'tp-upload',
            script: '../microservice-upload/dist/main.js',
            instances: 1,
            exec_mode: 'fork',
            watch: false,
            autorestart: false,
            max_memory_restart: '8192M',
            env: { ...commonEnv },
        },
        {
            name: 'tp-report',
            script: '../microservice-report/dist/main.js',
            instances: 1,
            exec_mode: 'fork',
            watch: false,
            max_memory_restart: '8192M',
            env: { ...commonEnv },
        },
    ]
};
