import {
  InboxOutlined,
  TeamOutlined,
  SettingOutlined,
  ContainerOutlined,
  FolderOpenOutlined,
  ShoppingOutlined,
  UserOutlined,
  InfoCircleOutlined,
  AppstoreAddOutlined,
  ShoppingCartOutlined,
  ToolOutlined,
  CheckCircleOutlined,
  ProfileOutlined,
  FileTextOutlined,
  TagOutlined,
  CreditCardOutlined,
  ClusterOutlined,
  ScheduleOutlined,
  ReconciliationOutlined,
  SafetyCertificateOutlined,
  DollarOutlined,
  GroupOutlined,
  IdcardOutlined,
  UserAddOutlined,
  SolutionOutlined,
  ProjectOutlined
} from '@ant-design/icons'

export const iconMapping = {
  ContainerOutlined: <ContainerOutlined style={{ fontSize: '18px' }} />,
  TeamOutlined: <TeamOutlined style={{ fontSize: '18px' }} />,
  SettingOutlined: <SettingOutlined style={{ fontSize: '18px' }} />,
  ShoppingOutlined: <ShoppingOutlined style={{ fontSize: '18px' }} />,
  InfoCircleOutlined: <InfoCircleOutlined style={{ fontSize: '18px' }} />,
  UserOutlined: <UserOutlined style={{ fontSize: '18px' }} />,
  FolderOpenOutlined: <FolderOpenOutlined style={{ fontSize: '18px' }} />,
  AppstoreAddOutlined: <AppstoreAddOutlined style={{ fontSize: '18px' }} />,
  ShoppingCartOutlined: <ShoppingCartOutlined style={{ fontSize: '18px' }} />,
  ToolOutlined: <ToolOutlined style={{ fontSize: '18px' }} />,
  CheckCircleOutlined: <CheckCircleOutlined style={{ fontSize: '18px' }} />,
  ProfileOutlined: <ProfileOutlined style={{ fontSize: '18px' }} />,
  InboxOutlined: <InboxOutlined style={{ fontSize: '18px' }} />,
  ClusterOutlined: <ClusterOutlined style={{ fontSize: '18px' }} />,
  SafetyCertificateOutlined: <SafetyCertificateOutlined style={{ fontSize: '18px' }} />,
  DollarOutlined: <DollarOutlined style={{ fontSize: '18px' }} />,
  GroupOutlined: <GroupOutlined style={{ fontSize: '18px' }} />,
  IdcardOutlined: <IdcardOutlined style={{ fontSize: '18px' }} />,
  UserAddOutlined: <UserAddOutlined style={{ fontSize: '18px' }} />,
  SolutionOutlined: <SolutionOutlined style={{ fontSize: '18px' }} />,
  ReconciliationOutlined: <ReconciliationOutlined style={{ fontSize: '18px' }} />,
  ProjectOutlined: <ProjectOutlined style={{ fontSize: '18px' }} />,
}
